os: osx
osx_image: xcode10.2
language: cpp

addons:
  homebrew:
    packages:
    - cmake
    - python3
    - conan

compiler:
  - clang

before_cache:
  - brew cleanup

cache:
  - directories:
    - $HOME/Library/Caches/Homebrew

install:
  - conan config install https://github.com/includeos/conan_config.git
  - conan --version

script:
  - conan create . includeos/latest -pr apple-clang-10-macos-toolchain
  - VERSION=$(conan inspect -a version . | cut -d " " -f 2)
  - |
    if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then
      conan upload --all vmbuild/$VERSION@includeos/latest -r includeos
    fi
    if [ -n "$TRAVIS_TAG" ]; then
      conan copy --all vmbuild/$VERSION@includeos/latest includeos/stable
      conan upload --all vmbuild/$VERSION@includeos/latest -r includeos
      conan upload --all vmbuild/$VERSION@includeos/stable -r includeos
    fi
